version: "3"

services:
  api:
    depends_on:
      - db
    ports:
      - 18080:80
    build:
      context: ./api/
    restart: always
    container_name: "my-api"
    networks:
      - myNet
    volumes:
      - ./api/src:/root/api
    working_dir: "/root/"
    tty: true

  db:
    image: mysql:8
    restart: always
    container_name: "my-db"
    ports:
      - 13306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tagudb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    networks:
      - myNet

  adminer:
    depends_on:
      - db
    image: adminer
    container_name: "my-adminer"
    restart: always
    ports:
      - 19999:8080
    networks:
      - myNet

networks:
  myNet:

volumes:
  db-data:
